version: '3'
services:
  # backend:
  #   image: node:16.15-alpine
  #   container_name: mentalcare-backend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./:/app
  #   working_dir: /app
  #   command: npm run start:dev
  db:
    image: mysql:8.0.33 
    container_name: mentalcare-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080    